name: Scheduled GitHub Pages Deployment

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual execution

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "shaumarquezrn@gmail.com"
          git config --global user.name "shaulamarquez"
          git checkout --orphan gh-pages
          git rm -rf .
          cp -r build/ .  # Make sure this path matches your build output
          git add .
          git commit -m "Deploy site"
          git push --force origin gh-pages
