name: Deploy to GitHub Pages

on:
  push:
    branches: main # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build production build (if applicable)
        run: npm run build # Or your build command

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3 # Use 'token' here
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build # Or the directory with your website files
          publish_branch: main # Deploy to the main branch
          cname: shaulamarquez.github.io # Optional
