name: Deploy to GitHub Pages

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at 00:00 UTC (midnight)  Adjust cron expression as needed

  # Optional: Add a manual trigger in case you need to run it outside of schedule
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Or your preferred Node.js version

      - name: Install dependencies
        run: npm ci

      - name: Build production build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Use the built-in GITHUB_TOKEN secret
          publish_dir: ./build # The directory containing your built website
          cname: shaulamarquez.github.io # Optional: Add your custom domain
